# Generated by Django 3.0.5 on 2020-05-03 19:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField()),
                ('price_cancel', models.FloatField()),
                ('sample', models.CharField(max_length=450, null=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255, null=True)),
                ('kind', models.CharField(max_length=25, null=True)),
                ('availability', models.CharField(max_length=55, null=True)),
                ('image', models.ImageField(blank=True, default='avater.jpg', null=True, upload_to='product/')),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('terminate', models.DateField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nile.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default='product.jpg', null=True, upload_to='product/')),
                ('image2', models.ImageField(blank=True, default='product.jpg', null=True, upload_to='product/')),
                ('image3', models.ImageField(blank=True, default='product.jpg', null=True, upload_to='product/')),
                ('image4', models.ImageField(blank=True, default='product.jpg', null=True, upload_to='product/')),
                ('image5', models.ImageField(blank=True, default='product.jpg', null=True, upload_to='product/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Nile.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Vacate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('via', models.CharField(default='None', max_length=255, null=True)),
                ('account', models.CharField(default='+255-0700-000-000', max_length=255, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(default='banner.jpg', null=True, upload_to='banners')),
                ('slogan', models.CharField(default='@Expore Beyond Limits.', max_length=255, null=True)),
                ('twitter', models.URLField(default='https://twitter.com/Voxmart1', max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('facebook', models.URLField(default='https://web.facebook.com/Voxmart-389747268420301', max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('instagram', models.URLField(default='https://www.instagram.com/voxmart/', max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('behance', models.URLField(default='https://www.linkedin.com/in/voxmart-online-396509186/', max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stipulate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('size01', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('color', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('color01', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('extent', models.PositiveIntegerField(default=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nile.Product')),
                ('seller', models.ForeignKey(db_column='seller', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stipulate_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('fild1', models.CharField(blank=True, default='None', max_length=25, null=True)),
                ('fild2', models.CharField(blank=True, default='None', max_length=25, null=True)),
                ('fild3', models.CharField(blank=True, default='None', max_length=25, null=True)),
                ('fild4', models.CharField(blank=True, default='None', max_length=25, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Nile.Product')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='Not Found', max_length=255, null=True)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('time', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nile.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('extract', models.PositiveIntegerField(default=0)),
                ('mine', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Chat With Robot', max_length=255, null=True)),
                ('slug', models.SlugField(default='Chat-With-Robot', unique=True)),
                ('receiver', models.ForeignKey(db_column='receiver', on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab1', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('tab2', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('tab3', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('tab4', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('tab5', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('det1', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('det2', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('det3', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('det4', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('det5', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Nile.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texting', models.TextField(default='Chat With Robot')),
                ('receiver', models.ForeignKey(db_column='receiver', on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_receiver', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nile.Post')),
                ('vendor', models.ForeignKey(db_column='vendor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('phone', models.CharField(default='+255-0712-258-369', max_length=255, null=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('remain', models.PositiveIntegerField(default=0)),
                ('holder', models.PositiveIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('spender', models.ForeignKey(db_column='spender', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invouce_spender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='None', max_length=30, null=True)),
                ('color1', models.CharField(blank=True, default='None', max_length=25, null=True)),
                ('color2', models.CharField(blank=True, default='None', max_length=25, null=True)),
                ('color3', models.CharField(blank=True, default='None', max_length=25, null=True)),
                ('color4', models.CharField(blank=True, default='None', max_length=25, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Nile.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avater', models.ImageField(default='avater.jpg', null=True, upload_to='profile')),
                ('about', models.TextField(default='@Please Update Your Profile To Access Market', null=True)),
                ('phone', models.CharField(default='UNKNOWN', max_length=255, null=True)),
                ('subscription', models.CharField(default='Titanium', max_length=255, null=True)),
                ('duration', models.IntegerField(default=15, null=True)),
                ('terminate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('entirety', models.IntegerField(default=0, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('professional', models.BooleanField(default=False)),
                ('institute', models.CharField(default='UNKNOWN', max_length=255, null=True)),
                ('region', models.CharField(default='UNKNOWN', max_length=255, null=True)),
                ('country', models.CharField(default='UNKNOWN', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nile.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
