# Generated by Django 3.0.5 on 2020-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0003_auto_20200509_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipulate',
            name='marked',
            field=models.CharField(default='None', max_length=250, unique=True),
        ),
    ]
