# Generated by Django 3.0.5 on 2020-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0004_stipulate_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipulate',
            name='terminate',
            field=models.BooleanField(default=True),
        ),
    ]
