# Generated by Django 3.0.5 on 2020-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0005_stipulate_terminate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipulate',
            name='terminate',
            field=models.BooleanField(default=False),
        ),
    ]
