# Generated by Django 3.0.5 on 2020-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0006_auto_20200514_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.CharField(default='market', max_length=255, null=True),
        ),
    ]
