# Generated by Django 3.0.5 on 2020-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0008_auto_20200515_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipulate',
            name='reference',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
