# Generated by Django 3.0.5 on 2020-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0009_auto_20200515_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipulate',
            name='charge',
            field=models.FloatField(default=0),
        ),
    ]
