# Generated by Django 3.0.5 on 2020-05-20 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nile', '0012_substitute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Leander Name', max_length=255, null=True)),
                ('minmun', models.PositiveIntegerField(default=0)),
                ('maxmum', models.PositiveIntegerField(default=0)),
                ('collateral', models.CharField(default='None', max_length=250)),
                ('duration', models.CharField(default='None', max_length=250)),
                ('monthly', models.CharField(default='None', max_length=2500)),
                ('weeksii', models.CharField(default='None', max_length=2500)),
                ('weeklyr', models.CharField(default='None', max_length=2500)),
                ('loaninfo', models.CharField(default='None', max_length=2500)),
                ('collatexpl', models.CharField(default='None', max_length=2500)),
                ('loanrepay', models.CharField(default='None', max_length=2500)),
                ('wereap', models.CharField(default='None', max_length=2500)),
                ('location', models.CharField(default='None', max_length=255, null=True)),
                ('terminate', models.DateField(null=True)),
                ('document', models.FileField(blank=True, default='loan/documents/main.txt', null=True, upload_to='loan/documents')),
                ('image', models.ImageField(default='product.jpg', null=True, upload_to='loan')),
                ('image2', models.ImageField(default='product.jpg', null=True, upload_to='loan')),
                ('image3', models.ImageField(default='product.jpg', null=True, upload_to='loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
