# Generated by Django 3.0.5 on 2020-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0014_lending_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='collateral',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='lending',
            name='collatexpl',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='duration',
            field=models.CharField(default='None', max_length=8),
        ),
        migrations.AlterField(
            model_name='lending',
            name='loaninfo',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='loanrepay',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='monthly',
            field=models.CharField(default='None', max_length=4),
        ),
        migrations.AlterField(
            model_name='lending',
            name='weeklyr',
            field=models.CharField(default='None', max_length=4),
        ),
        migrations.AlterField(
            model_name='lending',
            name='weeksii',
            field=models.CharField(default='None', max_length=4),
        ),
        migrations.AlterField(
            model_name='lending',
            name='wereap',
            field=models.TextField(default='None'),
        ),
    ]
