# Generated by Django 3.0.5 on 2020-05-28 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0015_auto_20200521_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adhere',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
