# Generated by Django 3.0.5 on 2020-05-29 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nile', '0016_client_adhere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avater',
            field=models.ImageField(default='avater.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='document',
            field=models.FileField(blank=True, default='loan/documents/main.txt', null=True, upload_to='loan/documents/'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='image',
            field=models.ImageField(default='product.jpg', null=True, upload_to='loan/'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='image2',
            field=models.ImageField(default='product.jpg', null=True, upload_to='loan/'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='image3',
            field=models.ImageField(default='product.jpg', null=True, upload_to='loan/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(default='banner.jpg', null=True, upload_to='banners/'),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255, null=True)),
                ('forename', models.CharField(default='None', max_length=255, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='product.jpg', null=True, upload_to='Movies/')),
                ('requrement', models.TextField(default='None')),
                ('location', models.TextField(default='None')),
                ('category', models.TextField(default='None')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
