# Generated by Django 3.0.5 on 2020-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0017_auto_20200529_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='location',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='requrement',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
