# Generated by Django 3.0.5 on 2020-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0018_auto_20200529_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='requrement',
            field=models.TextField(default='None'),
        ),
    ]
