# Generated by Django 3.0.5 on 2020-05-31 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0019_auto_20200529_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ended',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='software',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
