# Generated by Django 3.0.5 on 2020-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0020_auto_20200531_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='software',
            field=models.BooleanField(default=False),
        ),
    ]
