# Generated by Django 3.0.5 on 2020-05-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0021_auto_20200531_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adhere',
        ),
    ]
