# Generated by Django 3.0.5 on 2020-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0022_remove_client_adhere'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='movies', max_length=255),
        ),
    ]
