# Generated by Django 3.0.5 on 2020-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0023_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='None', max_length=255, null=True),
        ),
    ]
