# Generated by Django 3.0.5 on 2020-05-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0024_auto_20200531_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='Chat-With-Robot', unique=True),
        ),
    ]
