# Generated by Django 3.0.5 on 2020-06-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0025_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='terminate',
            field=models.DateField(null=True),
        ),
    ]
