# Generated by Django 3.0.5 on 2020-06-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0026_movie_terminate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=255, null=True)),
                ('slug', models.SlugField(default='voxmart-center-main', unique=True)),
                ('detail', models.CharField(default='None', max_length=2500)),
                ('poster', models.CharField(default='P.O.Box', max_length=255, null=True)),
                ('phone', models.CharField(default='+255-700-000-000', max_length=255, null=True)),
                ('phone2', models.CharField(default='+255-700-000-000', max_length=255, null=True)),
                ('phone3', models.CharField(default='+255-700-000-000', max_length=255, null=True)),
                ('email', models.EmailField(default='Voxmart@centers.admin', max_length=255, null=True)),
                ('email2', models.EmailField(default='Voxmart@centers.admin', max_length=255, null=True)),
                ('oppening', models.CharField(default='08:00 a.m - 05:30 p.m', max_length=255, null=True)),
                ('weekend', models.CharField(default='09:30 a.m - 03:30 p.m', max_length=255, null=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(default='Voxmart', max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nile.Center')),
            ],
        ),
    ]
