# Generated by Django 3.0.5 on 2020-06-29 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nile', '0028_auto_20200615_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default=None, max_length=255)),
                ('keyword2', models.CharField(default=None, max_length=255)),
                ('keyword3', models.CharField(default=None, max_length=255)),
                ('keyword4', models.CharField(default=None, max_length=255)),
                ('keyword5', models.CharField(default=None, max_length=255)),
                ('keyword6', models.CharField(default=None, max_length=255)),
                ('keyword7', models.CharField(default=None, max_length=255)),
                ('keyword8', models.CharField(default=None, max_length=255)),
                ('keyword9', models.CharField(default=None, max_length=255)),
                ('category', models.CharField(default=None, max_length=255)),
                ('category2', models.CharField(default=None, max_length=255)),
                ('category3', models.CharField(default=None, max_length=255)),
                ('category4', models.CharField(default=None, max_length=255)),
                ('category5', models.CharField(default=None, max_length=255)),
                ('category6', models.CharField(default=None, max_length=255)),
                ('lacation', models.CharField(default=None, max_length=255)),
                ('lacation2', models.CharField(default=None, max_length=255)),
                ('lacation3', models.CharField(default=None, max_length=255)),
                ('lacation4', models.CharField(default=None, max_length=255)),
                ('minmun', models.PositiveIntegerField(default=0)),
                ('maxmum', models.PositiveIntegerField(default=0)),
                ('average', models.DecimalField(decimal_places=16, max_digits=22)),
                ('terminate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
