# Generated by Django 3.0.5 on 2020-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0029_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='category2',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='category3',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='category4',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='category5',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='category6',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword2',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword3',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword4',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword5',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword6',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword7',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword8',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='keyword9',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='lacation',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='lacation2',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='lacation3',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='lacation4',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
