# Generated by Django 3.0.5 on 2020-06-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0030_auto_20200629_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='average',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
    ]
