# Generated by Django 3.0.5 on 2020-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0031_auto_20200629_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='lacation',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='lacation2',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='lacation3',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='lacation4',
        ),
        migrations.AddField(
            model_name='promotion',
            name='country',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='institute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='zone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
