# Generated by Django 3.0.5 on 2020-06-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0032_auto_20200630_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='institute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='zone',
            field=models.BooleanField(default=False),
        ),
    ]
