# Generated by Django 3.0.5 on 2020-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0033_auto_20200630_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='minmun',
        ),
        migrations.AddField(
            model_name='promotion',
            name='minmum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='maxmum',
            field=models.FloatField(default=0),
        ),
    ]
