# Generated by Django 3.0.5 on 2020-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0034_auto_20200630_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='minmum',
            field=models.FloatField(default=5000.0),
        ),
    ]
