# Generated by Django 3.0.5 on 2020-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nile', '0037_auto_20200630_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='category7',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
